[pytest]
markers =
    routers: Testes relacionados as rotas
    security: Testes relacionados a segurança
asyncio_default_fixture_loop_scope = session
filterwarnings =
    ignore:'asyncio.iscoroutinefunction' is deprecated:DeprecationWarning:slowapi
    ignore:'asyncio.AbstractEventLoopPolicy' is deprecated:DeprecationWarning:pytest_asyncio